language: php

git:
  depth: 1

cache:
  directories:
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"

php:
- 7.1
- 7.2
- 7.3

before_install:
- sudo apt-get install -y graphviz graphviz-dev

install:
- composer install

script:
- composer grumphp

after_success:
- phpenv config-rm xdebug.ini
- composer scrutinizer
